.drone.yml, README.md, docs/releases/v1.3.0.md, example/azure-example/main.tf, katalog/velero/README.md, katalog/velero/velero-aws/kustomization.yaml, katalog/velero/velero-azure/kustomization.yaml, katalog/velero/velero-base/kustomization.yaml, katalog/velero/velero-gcp/kustomization.yaml, katalog/velero/velero-on-prem/kustomization.yaml, katalog/velero/velero-restic/README.md, katalog/velero/velero-restic/kustomization.yaml, modules/azure-velero/README.md
Whit this PR the velero package inside this module got an update from 1.2.0 to the latest available version (1.3.1).
I will add the release docs ASAP
Pipeline passed: https://ci.sighup.io/sighupio/fury-kubernetes-dr/65/1/1
Thanks
=> Update velero 1.2.0 -> 1.3.1

modules/azure-velero/output.tf
The aim of this PR is to fix a typo in the `azure-velero` Terraform module output.
=> Fix typo in azure-velero outputs

modules/azure-velero/iam.tf
The aim of this PR is to add `Contributor` role in `velero_resource_group_name` to Velero Service Principal.
Since the generated `VolumeSnapshotLocation` rightfully uses `velero_resource_group_name` as target to save disk snapshots, the Service Principal used by Velero needs to have proper permissions to be able to write to that destination.
=> Updated azure-velero IAM permissions

modules/gcp-velero/output.tf
`BackupStorageLocation` and `VolumeSnapshotLocation` are namespaced resources: this PR adds the missing namespace in order to deploy them in the same namespace as Velero.
=> Add missing namespace in gcp-velero outputs

modules/azure-velero/output.tf, modules/azure-velero/velero.tf, modules/azure-velero/versions.tf
`BackupStorageLocation` and `VolumeSnapshotLocation` are namespaced resources: this PR adds the missing namespace in order to deploy them in the same namespace as Velero.
Furthermore, I've also replaced the internal `provider` block with a version constraint since it's not considered a good practice to include them in child modules as they may conflict with other version constraints declared in the root module. I've also relaxed the version constraint since I've tested the module with version 2.16 of `azurerm` provider.
Refs:
- https://www.terraform.io/docs/configuration/modules.html#providers-within-modules
=> Add missing namespace in azure-velero and remove provider block.

modules/aws-velero/output.tf
`BackupStorageLocation` and `VolumeSnapshotLocation` are namespaced resources: this PR adds the missing namespace in order to deploy them in the same namespace as Velero.
=> Add missing namespace in aws-velero outputs

.drone.yml, docs/releases/unreleased.md, example/azure-example/main.tf, modules/aws-velero/README.md, modules/aws-velero/output.tf, modules/azure-velero/README.md, modules/azure-velero/output.tf, modules/gcp-velero/README.md, modules/gcp-velero/output.tf
Hi team!
This PR aims to solve a bad dev experience (reported by the delivery team). The cloud-credentials output from the terraform modules returned cloud-credentials in plain text.
This PR changes the behaviour to output a Kubernetes Secret ready to apply to the cluster.
Before this PR, you run commands like:
```bash
$ terraform output cloud_credentials > /shared/cloud_credentials.config
$ kubectl create secret generic cloud-credentials --from-file=cloud=/shared/cloud_credentials.config --dry-run -o yaml | kubectl apply -f - -n kube-system
secret/cloud-credentials created
```
Now, to apply the cloud credentials to the cluster:
```bash
$ terraform output cloud_credentials > /shared/cloud_credentials.yaml
$ kubectl apply -f /shared/cloud_credentials.yaml
secret/cloud-credentials created …
```
=> Move cloud credentials from plain text to kubernetes secret (terraform module)

modules/gcp-velero/gcs.tf
I received this warning after a `terraform plan`: 
```
Warning: "bucket_policy_only": [DEPRECATED] Please use the uniform_bucket_level_access as this field has been renamed by Google.
```
I think it's should be pretty straightforward to fix.
=> Rename deprecated field

docs/releases/unreleased.md, modules/aws-velero/s3.tf, modules/eks-velero/s3.tf
Hi guys, i'm opening this PR because on DR buckets, versioning is not needed.
Object lifecycle is already managed by velero, if we leave versioning enabled the S3 bucket will grow indefinitely.
What do you think?
=> Disabling versioning on velero buckets

.drone.yml, README.md, docs/releases/unreleased.md, docs/releases/v1.6.0.md, katalog/velero/README.md, katalog/velero/velero-aws/kustomization.yaml, katalog/velero/velero-azure/kustomization.yaml, katalog/velero/velero-base/kustomization.yaml, katalog/velero/velero-gcp/kustomization.yaml, katalog/velero/velero-on-prem/kustomization.yaml, katalog/velero/velero-on-prem/minio/kustomization.yaml, katalog/velero/velero-on-prem/minio/sts.yaml, katalog/velero/velero-restic/kustomization.yaml
Ciao team!
This PR contains an update of the DR module. It has not a lot of changes, minor upgrade.
- Removed versioning on [AWS S3 bucket](../../modules/aws-velero).
- Kubernetes support:
- Deprecate Kubernetes 1.16 support.
- Kubernetes 1.19 is considered stable.
- Add tech-preview support to Kubernetes 1.20.
Pipeline: http://ci.sighup.io/sighupio/fury-kubernetes-dr/177
The upgrade procedure has been tested manually.
Thanks!
=> Release 1.6

docs/releases/unreleased.md, modules/aws-velero/README.md, modules/aws-velero/iam.tf, modules/aws-velero/input.tf, modules/aws-velero/output.tf, modules/aws-velero/s3.tf, modules/azure-velero/README.md, modules/azure-velero/iam.tf, modules/azure-velero/input.tf, modules/azure-velero/output.tf, modules/azure-velero/velero.tf, modules/eks-velero/README.md, modules/eks-velero/iam.tf, modules/eks-velero/input.tf, modules/eks-velero/output.tf, modules/eks-velero/s3.tf, modules/gcp-velero/README.md, modules/gcp-velero/gcs.tf, modules/gcp-velero/iam.tf, modules/gcp-velero/input.tf, modules/gcp-velero/output.tf
Following the same logic of https://github.com/sighupio/fury-kubernetes-furyagent/pull/1 I have simplified the interface of the terraform modules in the following way:
- allowing arbitrary `tags` 
- removing unnecessary inputs `env` and `name`
=> Simplify interface of all the terraform modules 

katalog/velero/velero-gcp/kustomization.yaml, katalog/velero/velero-gcp/plugin-patch.yaml, modules/gcp-velero/README.md, modules/gcp-velero/gcs.tf, modules/gcp-velero/iam.tf, modules/gcp-velero/input.tf, modules/gcp-velero/output.tf
As pointed out in https://github.com/sighupio/fury-kubernetes-dr/issues/30 the current implementation is lacking the necessary permission to perform snapshots of the volumes.
This PR addresses the aforemention issue by creating a custom role for velero with the necessary permissions:
```hcl
velero_role_permissions = [
"compute.disks.get",
"compute.disks.list",
"compute.disks.create",
"compute.disks.createSnapshot",
"compute.snapshots.get",
"compute.snapshots.list",
"compute.snapshots.create",
"compute.snapshots.useReadOnly",
"compute.snapshots.delete",
"compute.zones.get"
]
```
Check `iam.tf` for more details.
Moreover, this PR introduces the possibility to use **workload-identity** (https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity) instead of the hardcoded …
=> Fix missing permission and add workload identity in gcp velero

modules/aws-velero/README.md, modules/aws-velero/iam.tf, modules/aws-velero/input.tf, modules/aws-velero/output.tf
Re-adding the changes of @lnovara PR: https://github.com/sighupio/fury-kubernetes-dr/pull/19/ to extend `Velero on AWS` with the possibility to specify IAM Roles for ServiceAccount.
This functionality is currently being offered by [eks-velero](https://github.com/sighupio/fury-kubernetes-dr/tree/master/modules/eks-velero).  eks-velero will be deprecated and then removed in future module releases.
References:
- https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html
=> Re-introduce IAM Roles for ServiceAccount support to aws-velero

.drone.yml, README.md, build/builder/Dockerfile, docs/COMPATIBILITY_MATRIX.md, docs/CONTRIBUTING.md, docs/releases/v1.9.3.md, modules/aws-velero/output.tf
Trying to use the `aws-module` currently yields the following error:
```
│ Error: Invalid index
│
│   on ../vendor/modules/dr/aws-velero/output.tf line 18, in locals:
│   18:     aws_access_key_id=${aws_iam_access_key.velero_backup.0.id}
│     ├────────────────
│     │ aws_iam_access_key.velero_backup is empty tuple
│
│ The given key does not identify an element in this collection value.
╵
╷
│ Error: Invalid index
│
│   on ../vendor/modules/dr/aws-velero/output.tf line 19, in locals:
│   19:     aws_secret_access_key=${aws_iam_access_key.velero_backup.0.secret}
│     ├────────────────
│     │ aws_iam_access_key.velero_backup is empty tuple
│
│ The given key does not identify an element in this collection value.
```
The aim of this PR is to fix this error and bring a couple of additional …
=> Fix broken aws-velero Terraform module

katalog/velero/velero-base/dashboards/MAINTENANCE.md, katalog/velero/velero-base/dashboards/velero.json
- Use the official Grafana Dashboard for Velero from Tanzu.
- Add MAINTENANCE file for the dashboard.
Fixes #50 - the official dashboard does not have a widget for the non-existing metric.
=> fix: update grafana dashboard

katalog/velero/velero-base/alert-rules.yaml
Align the field used to describe the alert with what we are using in the rest of the alerts and in the AlertManager template for the Slack notifications.
=> fix(monitoring): fix alert description field

katalog/velero/velero-base/dashboards/kustomization.yaml
Add annotation to put the module's Grafana dashboards inside the "Disaster Recovery" folder for better organization.
=> feat: put dashboards in "Disaster Recovery" grafana folder

README.md, katalog/etcd-backup-pvc/MAINTENANCE.md, katalog/etcd-backup-pvc/README.md, katalog/etcd-backup-pvc/cronjob.yaml, katalog/etcd-backup-pvc/kustomization.yaml, katalog/etcd-backup-s3/README.md, katalog/etcd-backup-s3/cronjob.yaml, katalog/etcd-backup-s3/kustomization.yaml
This PR adds support for saving ETCD snapshots to an existing PersistentVolumeClaim.
Relates: https://github.com/sighupio/product-management/issues/638
This feature allows users to backup the ETCD database to an existing in-cluster PersistentVolumeClaim.
Hopefully nothing 🙈
Add more backends.
=> Add etcd-backup-pvc

README.md, docs/releases/v1.10.0.md, docs/releases/v1.10.1.md, docs/releases/v1.11.0.md, docs/releases/v1.2.0.md, docs/releases/v1.5.0.md, docs/releases/v1.6.0.md, docs/releases/v1.7.0.md, docs/releases/v1.8.0.md, docs/releases/v1.9.0.md, docs/releases/v1.9.1.md, docs/releases/v1.9.2.md, docs/releases/v1.9.3.md, docs/releases/v2.0.0.md, docs/releases/v2.1.0.md, docs/releases/v2.2.0.md, docs/releases/v2.3.0.md, docs/releases/v2.4.0.md, docs/releases/v3.0.0.md, docs/releases/v3.1.0.md, examples/registry-override/README.md, katalog/etcd-backup-pvc/MAINTENANCE.md, katalog/etcd-backup-s3/MAINTENANCE.md, katalog/velero/README.md, katalog/velero/velero-aws/README.md, katalog/velero/velero-azure/README.md, katalog/velero/velero-gcp/README.md
The goal of this PR is to rebrand KFD to SIGHUP Distribution (SKD).
No tests are needed.
=> chore: rename Fury to SIGHUP Distribution

README.md, docs/releases/v3.1.0.md
Fix the release docs to include both `etcd-backup-s3` and `etcd-backup-pvc`.
During the release I figured that the docs for `etcd-backup-s3` and `etcd-backup-pvc` were missing. This PR readds them.
None.
None.
None.
=> docs: fix release docs for etcd-backup-s3 and etcd-backup-pvc

katalog/velero/velero-on-prem/storageLocation.yaml
Make the default BackupStorageLocation the explicit default instead of relying on Velero heuristics so Velero won't be logging a misleading error that there's no default location.
Fixes #90
See summary
None
None
=> fix: set default BackupStorageLocation explicitly
